### ISSUE TITLE
Question: upgrading to Elasticsearch 1.5.2

### ISSUE THREAD

**Issue by cata** [garvincasimir/Elasticsearch-Azure-PAAS-Plugin#1]
Hi Garvin,

I've tried the plugin with ES 1.5.2 and it fails to load, due to a breaking change in the `ZenDiscovery` constructor - it takes and additional argument. My Java knowledge is near-zero - but I installed Maven and Eclipse and I think I fixed the issue - the constructor seems to be called by an ES DI mechanism, so adding the missing argument and passing it to the base class seems sufficient in this particular case.

I have yet to test the change in a real deployment. Before I do that and submit a PR: are you OK with losing compatibility with 1.4.x in the next version? Would you like to manage this type of breaking change in a different manner (e.g. two versions of the plug-in evolving in parallel)?

**Comment by garvincasimir** [comment]
Hi @ca-ta I synced a commit earlier today which does what you suggested. I will also be uploading a new NuGet package for the main project. It is unfortunate that plugins are stuck with one specific version but I don't think it is worth it at this point to maintain multiple versions. If someone really wants to use an older version of Elasticsearch I am willing to help them create a build. That being said, I should probably do a better job in tagging this repo.

**Comment by garvincasimir** [comment]
Had I known you had a pull request on the way I could have focused on other things. We just duplicated work.

**Comment by cata** [comment]
@garvincasimir - I hear you! Quite the coincidence (I guess it's not that surprising after all, since we were both looking at the repo for the last day or so). Oh well, I've finally got to use Eclipse and Maven, so not a total loss :-)
I'll close the pull requests

**Comment by garvincasimir** [comment]
I was testing the new NuGet stuff and decided it was a good time to upgrade while I was deep in it.

**Comment by cata** [comment]
Yup, testing is how I ended up doing the same thing. Too funny :-)
